### ISSUE TITLE
Peek top bar anywhere

### ISSUE THREAD

**Issue by jacksongoode** [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#11]
Over the past years there has been an extension that allowed the hiding of the top bar https://gitlab.gnome.org/tuxor1337/hidetopbar but has been fairly unmaintained for the last 10 Gnome releases. It would be cool to see this extension offer a more maintained alternative to peek the top bar not just on fullscreen applications, but everywhere.

**Comment by marcinjahn** [comment]
Hi @jacksongoode I’m not planning to extend the functionality of this extension outside of what it was supposed to do - show toolbar while full screen content is playing. 
The extension you linked to seems to be kinda alive - last commit was pushed just a few months ago. I guess it will not run on Gnome 45 due to breaking changes there, but I guess maintainers or someone from community could update it.
