### ISSUE TITLE
Wrong name of .gschema.xml

### ISSUE THREAD

**Issue by doppelhelix** [marcinjahn/gnome-peek-top-bar-on-fullscreen-extension#3]
Right now the filename is 
`org.gnome.shell.extensions.quicksettings-audio-devices-renamer.gschema.xml`
Wouldn't it be better to rename it to 
`org.gnome.shell.extensions.peek-top-bar-on-fullscreen.gschema.xml`?

**Comment by marcinjahn** [comment]
Hi @doppelhelix, thanks for spotting that. Actually, this file can just be completely removed, since it is needed only for defining configuration options. This extension is not configurable in any way at the moment, so it can just go. This file, together with a bunch of others, has been copied from [Audio Devices Renamer](https://github.com/marcinjahn/gnome-quicksettings-audio-devices-renamer-extension), to skip the tedious process of creating everything from scratch.

If you want, feel free to submit a PR that removes that file. Otherwise, I'll do it sometime later.

**Comment by doppelhelix** [comment]
Since I do not know anything about npm and the underlying build-process, I do not dare to make a PR

**Comment by marcinjahn** [comment]
@doppelhelix The only thing to do in the PR would be the removal of [this file](https://github.com/marcinjahn/gnome-peek-top-bar-on-fullscreen-extension/blob/main/resources/schemas/org.gnome.shell.extensions.quicksettings-audio-devices-renamer.gschema.xml). No need to touch the `package.json`. The commands there are generic, and don't need to be change. If there is no schema, it will just no compile it, and it's totally fine.

**Comment by doppelhelix** [comment]
ok

**Comment by marcinjahn** [comment]
It should be fine now, empty directories will not be fetched, I added a keeper file there, and it should be alright

**Comment by doppelhelix** [comment]
~~~
No schema files found: doing nothing.
~~~
Thanks a lot

**Comment by marcinjahn** [comment]
@doppelhelix, fyi, in the end I removed the `schemas`  directory entirely since I got such request during extension review on extensions.gnome.org/.
